import { GoogleGenerativeAI } from "@google/generative-ai";

// In Vite, use import.meta.env. Variables must be prefixed with VITE_ in .env
const apiKey = import.meta.env.VITE_GEMINI_API_KEY || "";
const genAI = new GoogleGenerativeAI(apiKey);

export async function transcribeAudio(audioData) {
  // Mock transcription for now
  return "This is a mock transcript generated by SocialTranscribe AI.";
}

export async function summarizeTranscript(transcript) {
  // Mock summary for now
  return "This is a mock summary of the video content.";
}
