import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function transcribeAudio(audioData) {
  // Mock transcription for now
  return "This is a mock transcript generated by SocialTranscribe AI.";
}

export async function summarizeTranscript(transcript) {
  // Mock summary for now
  return "This is a mock summary of the video content.";
}
